### ISSUE TITLE
Grpc error: Header size exceeded max allowed size (8192) when using Pseudonymization

### ISSUE THREAD

**Issue by viniciusccarvalho** [googleapis/java-dlp#206] opened 2020-06-16 18:31 UTC
#### Environment details

1. Specify the API at the beginning of the title. For example, "Cloud DLP: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: MacOS
3. Java version: 11
4. dlp version(s): 1.1.4

#### Steps to reproduce

I was adapting the code to do Pseudonymization from https://cloud.google.com/dlp/docs/pseudonymization and I keep getting a GRPC error on headers being bigger than 8192

Besides the fact that I'm sending two fields instead of one (but only one row) and I'm using Alphanumeric as then alphabet, can't see anything that is so different from the examples. Not sure why it fails.

#### Code example

```kotlin
		val kmsKeyName = "<redacted>"
//uses kms to encrypt a 16 char key
		val key = kmsTemplate.encrypt("my16charkey")
//utility function just build a table with 2 headers (email, phoneNumber) and add one row to it
		val table = entityToTable(entity)
		val item = ContentItem.newBuilder().setTable(table).build()
		val kmsWrappedCryptoKey = KmsWrappedCryptoKey.newBuilder()
				.setWrappedKey(ByteString.copyFrom(Base64Utils.decodeFromString(key)))
				.setCryptoKeyName(kmsKeyName)
				.build()
		val cryptoKey = CryptoKey.newBuilder().setKmsWrapped(kmsWrappedCryptoKey).build()
		val cryptoReplaceFfxFpeConfig =
				CryptoReplaceFfxFpeConfig.newBuilder()
						.setCryptoKey(cryptoKey)
						.setCommonAlphabet(CryptoReplaceFfxFpeConfig.FfxCommonNativeAlphabet.ALPHA_NUMERIC)
						.build()
		val primitiveTransformation =
				PrimitiveTransformation.newBuilder()
						.setCryptoReplaceFfxFpeConfig(cryptoReplaceFfxFpeConfig)
						.build()
		val fields = listOf(FieldId.newBuilder().setName("email").build(),
				FieldId.newBuilder().setName("phoneNumber").build())
		val fieldTransformation =
				FieldTransformation.newBuilder()
						.setPrimitiveTransformation(primitiveTransformation)
						.addAllFields(fields)
						.build()
		val transformations =
				RecordTransformations.newBuilder().addFieldTransformations(fieldTransformation).build()
		val deidentifyConfig =
				DeidentifyConfig.newBuilder().setRecordTransformations(transformations).build()
		val request =
				DeidentifyContentRequest.newBuilder()
						.setParent(LocationName.of(projectIdProvider.projectId, "global").toString())
						.setItem(item)
						.setDeidentifyConfig(deidentifyConfig)
						.build()
		val response = dlp.deidentifyContent(request)
		println("Table after format-preserving encryption: " + response.item.table)
```

#### Stack trace
```
Caused by: io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception$HeaderListSizeException: Header size exceeded max allowed size (8192)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception.headerListSizeError(Http2Exception.java:189)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2CodecUtil.headerListSizeExceeded(Http2CodecUtil.java:233)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.HpackDecoder$Http2HeadersSink.finish(HpackDecoder.java:546)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.HpackDecoder.decode(HpackDecoder.java:133)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2HeadersDecoder.decodeHeaders(DefaultHttp2HeadersDecoder.java:126)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader$HeadersBlockBuilder.headers(DefaultHttp2FrameReader.java:743)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader$2.processFragment(DefaultHttp2FrameReader.java:483)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:491)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:254)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1486)
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```

#### External references such as API reference guides

- ?

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by chingor13** [comment] 2021-03-10 23:11
Sorry for the late reply. I'm unable to reproduce this error on Java 11 on OSX at version 1.1.4 of google-cloud-dlp. At this point, DLP and gRPC are many versions ahead so I'm going to close this.

If this is still happening, please reopen with a runnable sample that reproduce this (dependencies). We run a similar sample as part of our CI flow (https://github.com/googleapis/java-dlp/blob/master/samples/snippets/src/main/java/dlp/snippets/DeIdentifyWithFpe.java) which has been consistently passing.

**Closed by chingor13** 2021-03-10 23:11 UTC
Labels: :rotating_light:, api: dlp, priority: p2, type: bug
